name: CI/CD for React App

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: shubhsharma99/react-app/.github/workflows/react-reusable-workflow.yml@main
    with:
      react-node-version: '20.x'
