name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-reusable:
    uses: your-organization/organization-workflows/.github/workflows/reusable-react-ci.yml@main
    with:
      example-input: "Hello from calling workflow"
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
