name: React Reusable Workflow

on:
  workflow_call:
    inputs:
      react-node-version:
        description: 'Node.js version to use'
        required: true
        default: '20.x'
        type: string   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.react-node-version }}   

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build
